# -*- coding: utf-8 -*-
"""ATIVIDADE PRATICA SEGUNDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrxyfXqKwdsFj806zDx4hZY-AseiaGUE
"""

import re

def validar_email(email):
    # Regex que atende aos requisitos básicos e aos desafios propostos:
    # 1. ^[a-zA-Z0-9_]+             -> Inicia com alfanumérico ou underline (impede ponto no início)
    # 2. ([.-][a-zA-Z0-9_]+)*       -> Permite . ou - no meio, mas exige que seja seguido por alfanumérico (impede 2 pontos seguidos e ponto antes do @)
    # 3. @                          -> Símbolo obrigatório
    # 4. ([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+ -> Partes do domínio. Inicia/termina com alfanum, permite hífen no meio (impede hífen nas pontas)
    # 5. [a-zA-Z]{2,}$              -> TLD (extensão) final com no mínimo 2 letras
    padrao_regex = r"^[a-zA-Z0-9_]+([.-][a-zA-Z0-9_]+)*@([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$"

    # Aprova e retorna se ele é valido
    if re.match(padrao_regex, email):
        return True, "Formato válido."


    # se falhar ele ja retorna o porque de falhar
    if "@" not in email:
        return False, "Falta o símbolo '@'."

    partes = email.split('@')
    if len(partes) > 2:
        return False, "Contém mais de um símbolo '@'."

    usuario, dominio = partes

    if usuario.startswith('.'):
        return False, "O nome de usuário não pode começar com ponto."
    if usuario.endswith('.'):
        return False, "O nome de usuário não pode terminar com ponto (imediatamente antes do '@')."
    if ".." in email:
        return False, "O endereço não pode conter pontos consecutivos ('..')."

    if not re.match(r"^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$", dominio):
        if "." not in dominio:
            return False, "O domínio está incompleto (falta a extensão de topo, ex: '.com')."

        for parte in dominio.split('.')[:-1]: # Verifica cada parte antes da extensão final
            if parte.startswith('-') or parte.endswith('-'):
                return False, "Nenhuma parte do domínio pode começar ou terminar com hífen."
        return False, "Estrutura de domínio inválida."

    return False, "Possui caracteres não permitidos ou formatação estrutural incorreta."


def main():
    validos = []
    invalidos = []

    print("=== Validador de E-mails com Regex ===")
    print("Digite 5 endereços de e-mail para análise:\n")

    # 1. Solicita cinco endereços
    for i in range(5):
        email = input(f"E-mail {i+1}: ").strip()

        # 2. Valida o endereço
        is_valid, motivo = validar_email(email)

        # 3. Armazena separadamente
        if is_valid:
            validos.append(email)
        else:
            invalidos.append((email, motivo))

    # Apresenta os resultados e explica o que não funcionou
    print("\n" + "="*40 + "\nRESULTADO DA ANÁLISE\n" + "="*40)

    print("\n✅ E-MAILS VÁLIDOS:")
    if not validos:
        print("Nenhum e-mail válido encontrado.")
    for v in validos:
        print(f" - {v}")

    print("\n❌ E-MAILS INVÁLIDOS E MOTIVOS:")
    if not invalidos:
        print("Nenhum e-mail inválido encontrado.")
    for inv, motivo in invalidos:
        print(f" - {inv}")
        print(f"   Motivo: {motivo}")

if __name__ == "__main__":
    main()